### ISSUE TITLE
outputFile functionality broken

### ISSUE THREAD

**Issue by perry-mitchell** [MichaelKohler/volunteer-contributions-fetch#10]
Hi, it seems like the `outputFile` functionality is not working. I get errors no matter what path I specify (ENOENT).

* If the file doesn't exist, I get `[Error: ENOENT: no such file or directory, open '/tmp/test.json']`
* If the file does exist, and is an empty object, I get `TypeError: existingContributions.find is not a function`

So I'm not sure what I'm supposed to do here. Shouldn't it create the file itself?

What would be better, imo, would be to output it to a variable and let the user deal with the data instead of forcing the consumer to provide filesystem access.

**Comment by MichaelKohler** [comment]
Hi there, thanks for filing this issue. Would love to hear more about how you found this project :)

It indeed currently does not create the file if it does not exist. I'd agree it should. The expected "empty" content would be an empty array: `[]`. So that is certainly a bug and should be fixed.

I also like the idea of returning the data by default, as that would indeed give more control. Maybe that could be the default behavior in any case? Even if somebody defines an `outputFile`, there is no harm in returning the data. Completely removing `outoutFile` in favor of this approach of course would also be possible but would be a breaking change. I like the idea of having that as default though. Note that this would also need a fallback as there wouldn't be a source for existing contributions. Do you think that it should also accept a parameter with existing contributions then?

Would you be interested in contributing those fixes/changes? I'd definitely be happy to give pointers and review it.

Thanks!

**Comment by MichaelKohler** [comment]
@perry-mitchell Thanks again for providing this bug report. Would you be interested in contributing a fix for this? I might get to it within the next 2 weeks or so, but if you want to, I'd be happy to help you as needed :)

**Comment by MichaelKohler** [comment]
Thanks again for reporting this. This is now fixed and improved in https://github.com/MichaelKohler/volunteer-contributions-fetch/releases/tag/v2.5.0.
